Repository uPortal-Project/uPortal-start, pull requests merged in 2019-07, with the labels that each got.

#338 feat(jjwt): Add comments in uPortal.properties to note how to generat…
  etc/portal/notification.properties
  etc/portal/uPortal.properties
Labels: documentation, enhancement, work in progress

#340 docs(data): How to lock down non-admin layouts
  docs/en/data/index.md
  docs/en/data/lockdown-layouts.md
Labels: documentation

#323 chore: esup-filemanager 4.0.0 + required spring change to work with CAS
  etc/portal/global.properties
  gradle.properties
  overlays/esup-filemanager/src/main/webapp/WEB-INF/context/drives.xml
Labels: bug

#350 doc(docker): Initial write-up on Docker usage
  docs/en/sysadmin/docker.md
Labels: documentation, work in progress

#351 docs(tomcat): Add doc on how to externalize Tomcat config
  docs/en/sysadmin/tomcat-env-vars.md
Labels: documentation

#349 chore(prop): Add signatureAlgorithm to uPortal.properties
  etc/portal/uPortal.properties
Labels: documentation

#352 doc(rs): Describe adding and using static files
  docs/en/content/resource-server.md
  docs/en/content/webjars.md
Labels: documentation
